In [3]:
import numpy as np
import pandas as pd

data = pd.read_csv('data.csv')
data = data.set_index('date')# 将date设置为index

In [4]:
data.head()

,0:00:00,1:00:00,2:00:00,3:00:00,4:00:00,5:00:00,6:00:00,7:00:00,8:00:00,9:00:00,...,14:00:00,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00
date,,,,,,,,,,,,,,,,,,,,,
2018-01-01,498.849711,568.722783,571.976601,565.685116,557.767855,538.997216,503.920159,501.880084,409.504079,348.658712,...,162.392865,152.237241,135.113763,154.245366,91.016745,89.072603,136.065144,134.285779,136.525736,136.858397
2018-01-02,138.682982,138.687231,138.587451,137.097339,147.389217,171.469343,181.241544,190.673310,188.913216,144.557751,...,254.336475,231.993377,248.400037,208.950062,123.019135,160.193379,166.044810,184.997083,220.211629,283.994959
2018-01-03,276.029268,392.131019,227.464215,183.000956,179.681595,259.146483,313.583010,280.530973,272.014769,283.858254,...,221.786216,213.833589,217.264496,241.365621,391.289195,299.895193,290.255545,404.356423,378.395155,417.823121
2018-01-04,367.463649,409.269834,286.109966,255.044034,247.185864,276.671340,231.293024,195.366763,156.425822,173.028752,...,200.999143,214.316448,188.089719,143.846772,152.849671,190.170611,213.500693,229.917947,230.990019,283.032312
2018-01-05,232.290388,220.279973,161.365365,136.924702,134.806185,133.233337,128.350867,122.988473,121.982310,106.687148,...,247.026774,248.543168,239.240107,224.641310,226.861131,224.503468,240.723608,237.417091,253.115324,295.503727